### ISSUE TITLE
Look into updating kubernetes to the 1.7.* releases

### ISSUE THREAD

**Issue by dragan** [scipian/quoins#38]
This is a spike to see what will need to change to upgrade the kubernetes quoin to the 1.7.* releases. I would also like the #36 to be a part of the upgrade path.

**Comment by dragan** [comment]
#35 relates to this as well and should be included as part of the work.

**Comment by dragan** [comment]
I'm moving the priority of this up as I want to get this done to ease the bootstrapping scipian/community#20 process.

**Comment by dragan** [comment]
[WIP] Spike Discovery:

- [ ] Continue using Container Linux i.e. CoreOS
- [ ] Provision Container Linux using Ignition and move off of cloud configs #53
- [ ] Run etcd as part of the control plane #36
- [ ] Use upstream k8s binaries for kubelet #35
- [ ] Install kubectl as part of the provisioning
- [ ] [Enable Role-Based Access Control (“RBAC”)][rbac]
- [ ] [Enable Volume Claims][volume-claims]
- [ ] [Enable Stateful Sets][stateful-sets]
- [ ] Enable the Admin UI

[rbac]: https://kubernetes.io/docs/admin/authorization/rbac/
[volume-claims]: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
[stateful-sets]: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
