### ISSUE TITLE
Make kubernetes & etcd quoins more region aware

### ISSUE THREAD

**Issue by dragan** [scipian/quoins#46]
When enhancing our existing quoins to be more configurable as far as docker images and policy changes. We really shouldn't be pushing these variables down to the quoin user, instead we should allow our quoins to be more region aware.

- [x] Templatize assume-role-policy #24
- [x] Reflect policy variables in etcd quoin #29
- [x] Configurable locations for docker images #60
